version: '3'

services:
  dsvw:
    image: vbolzanifg/dsvw-letsbit:latest
    ports:
      - 65412:65412
  
  waf:
    image: owasp/modsecurity-crs:nginx
    environment:
      - BACKEND=http://dsvw:65412
      - MODSEC_AUDIT_ENGINE=On
      - PARANOIA=3
    ports:
      - 80:80