name: "Build and push Docker image"

on:
    push:
        branches:
            - master

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build and push
              id: build
              uses: cloudposse/github-action-docker-build-push@main
              with:
                registry: registry.hub.docker.com
                organization: vbolzanifg
                repository: dsvw-letsbit
                login: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
                tags: latest

    deploy_test:
      runs-on: ubuntu-latest
      needs: build_and_push

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Deploy package generation
          run: zip -j deploy.zip ./deploy/test/*

        - name: Deploy
          uses: einaregilsson/beanstalk-deploy@v21
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            application_name: dsvw-test
            environment_name: Dsvw-test-env
            version_label: ${{ github.sha }}-test
            region: us-east-1
            deployment_package: deploy.zip

    healthcheck_test:
      runs-on: ubuntu-latest
      needs: deploy_test
      steps:
        - name: Healthcheck
          run: curl http://dsvw-test.us-east-1.elasticbeanstalk.com/

    dast-test:
      runs-on: ubuntu-latest
      needs: healthcheck_test
      steps:
        - name: ZAP Scan
          uses: zaproxy/action-baseline@master
          with:
            token: ${{ secrets.NOTIFICATIONS_ACCESS_GIT }}
            target: http://dsvw-test.us-east-1.elasticbeanstalk.com/
            cmd_options: '-a'
            fail_action: 'false'
            issue_title: 'Analisis de seguridad en entorno de test'

    deploy_prod:
      runs-on: ubuntu-latest
      needs: build_and_push
    
      steps:
        - name: Checkout
          uses: actions/checkout@v2
    
        - name: Deploy package generation
          run: zip -j deploy.zip ./deploy/prod/*
    
        - name: Deploy
          uses: einaregilsson/beanstalk-deploy@v21
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            application_name: dsvw-test
            environment_name: Dsvw-prod-env
            version_label: ${{ github.sha }}-prod
            region: us-east-1
            deployment_package: deploy.zip