name: "Build and push Docker image"

on:
    push:
        branches:
            - master

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build and push
              id: build
              uses: cloudposse/github-action-docker-build-push@main
              with:
                registry: registry.hub.docker.com
                organization: vbolzanifg
                repository: dsvw-letsbit
                login: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
                tags: latest
